[package]
name = "kohonen"
version = "0.1.0"
authors = ["m-lange <martin_lange_@gmx.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"
rand = "0.5.5"
easy_graph = { path = "../easy_graph", version = "0.1.0" }

[dev-dependencies]
statistical = "1.0.0"

