.\target\release\kohonen.exe ^
--file example_data/iris.csv ^
--size 20 16 ^
--episodes 5000 ^
--layers "sepal_length sepal_width petal_length petal_width" "species" ^
--categ 0 1 ^
--norm gauss none ^
--weights 1 1 ^
--alpha 0.2 0.01 lin ^
--radius 8 0.7 lin ^
--decay 0.2 0.001 exp ^
--neigh gauss
