..\target\release\kohonen.exe ^
--file ..\example_data\countries.csv ^
--size 30 20 ^
--episodes 10000 ^
--layers "child_mort_2010 birth_p_1000 GNI LifeExpectancy PopGrowth PopUrbanized PopGrowthUrb AdultLiteracy PrimSchool Income_low_40 Income_high_20" ^
--categ 0 ^
--norm gauss ^
--weights 1 ^
--alpha 0.2 0.01 lin ^
--radius 10 0.5 lin ^
--decay 0.2 0.001 exp ^
--neigh gauss ^
--no-data -
