..\target\release\kohonen.exe ^
--file ..\example_data\iris.csv ^
--size 20 16 ^
--episodes 2500 ^
--layers "sepal_length sepal_width petal_length petal_width" "species" ^
--categ false true ^
--norm gauss none ^
--weights 1 1 ^
--alpha 0.2 0.01 lin ^
--radius 8 0.7 lin ^
--decay 0.2 0.001 exp ^
--neigh gauss ^
--output ..\example_data\iris
