[package]
name = "kohvis"
version = "0.1.0"
authors = ["m-lange <martin_lange_@gmx.net>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
gdnative = "0.8"
euclid = "0.20"
structopt = "0.3"
kohonen = { path = ".." }